name: dev

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  test:
    name: code quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: 'Get dependencies'
        run: flutter pub get

      - name: 'Code generation for example folder'
        run: cd example && dart pub run build_runner build

      - name: 'Check code style'
        run: dart format --set-exit-if-changed .

      - name: 'Analyze'
        run: flutter analyze
  
  package-analysis:
    name: package points
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}