name: dev

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  test:
    name: code quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
          cache: true

      - name: 'Get dependencies'
        run: flutter pub get

      - name: 'Check code style'
        run: flutter format --set-exit-if-changed .

      - name: 'Analyze'
        run: flutter analyze

      - name: 'Dart Code Metrics - Reports code metrics, rules and anti-patterns violations.'
        run: flutter pub run dart_code_metrics:metrics analyze lib
  
  pana:
    name: pana
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0

      - name: Install Dependencies
        run: |
          flutter packages get
          flutter pub global activate pana
          sudo apt-get install webp
      - name: Verify Pub Score
        run: ../tool/verify_pub_score.sh